"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
$username\
[](bg:sapphire fg:surface0)\
$directory\
[](fg:sapphire bg:teal)\
$git_branch\
$git_status\
[](fg:teal bg:blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:blue bg:lavender)\
$docker_context\
[](fg:lavender bg:sapphire)\
$time\
[ ](fg:sapphire)\
$line_break$character"""

palette = 'catppuccin_ocean'

[palettes.catppuccin_ocean]
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"

teal = "#94e2d5"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"

green = "#a6e3a1"
yellow = "#f9e2af"
red = "#f38ba8" # giữ lại cho error
peach = "#fab387" # giữ lại accent nhẹ

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Arch = ""       # biểu tượng Arch Linux phổ biến
Artix = ""      # có thể dùng riêng nếu muốn
Linux = "󰌽"      # fallback cho các distro khác

[username]
show_always = true
style_user = "bg:surface0 fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:sapphire"
format = "[  $path ]($style)"
truncation_symbol = "…/"
truncation_length = 8

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch ](fg:base bg:teal)]($style)'

[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind )](fg:base bg:teal)]($style)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[golang]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[python]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[docker_context]
symbol = ""
style = "bg:lavender"
format = '[[ $symbol( $context) ](fg:base bg:lavender)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:sapphire fg:base"
format = '[[  $time ](fg:base bg:sapphire)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:blue)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:creen)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
